enum JuniorFeelingsActionType {
  GET_JUNIOR_FEELINGS_REQUEST = 'GET_JUNIOR_FEELINGS_REQUEST',
  GET_JUNIOR_FEELINGS_SUCCEEDED = 'GET_JUNIOR_FEELINGS_SUCCEEDED',
  GET_JUNIOR_FEELINGS_FAILED = 'GET_JUNIOR_FEELINGS_FAILED',
}

export default JuniorFeelingsActionType;
