enum displayDateActionType {
  NEXT_WEEK = 'NEXT_WEEKLY',
  PREVIOUS_WEEK = 'PREVIOUS_WEEKLY',
  NEXT_MONTH = 'NEXT_MONTH',
  PREVIOUS_MONTH = 'PREVIOUS_MONTH',
  CHANGE_WEEK_SPAN_BUTTON_CLICKED = 'CHANGE_WEEK_SPAN_BUTTON_CLICKED',
  CHANGE_MONTH_BUTTON_CLICKED = 'CHANGE_MONTH_BUTTON_CLICKED',
  TAB_CLICKED = 'TAB_CLICKED',
  UPDATE_DISPLAY_SPAN = 'UPDATE_DISPLAY_SPAN',
  UPDATE_DISPLAY_TAB = 'UPDATE_DISPLAY_TAB',
  RESET_DATE = 'RESET_DATE',
}

export default displayDateActionType;
