enum displayDateActionType {
  NEXT_WEEK = 'NEXT_WEEKLY',
  PREVIOUS_WEEK = 'PREVIOUS_WEEKLY',
  NEXT_MONTH = 'NEXT_MONTH',
  PREVIOUS_MONTH = 'PREVIOUS_MONTH',
  CHANGE_DATE_SPAN_BUTTON_CLICKED = 'CHANGE_DATE_SPAN_BUTTON_CLICKED',
  TAB_CLICKED = 'TAB_CLICKED',
}

export default displayDateActionType;
