enum DepartmentsActionType {
  GET_DEPARTMENTS_REQUEST = 'GET_DEPARTMENTS_REQUEST',
  GET_DEPARTMENTS_SUCCEEDED = 'GET_DEPARTMENTS_SUCCEEDED',
  GET_DEPARTMENTS_FAILED = 'GET_DEPARTMENTS_FAILED',
}

export default DepartmentsActionType;
