enum FeelingsActionType {
  GET_FEELINGS_REQUEST = 'GET_FEELINGS_REQUEST',
  GET_FEELINGS_SUCCEEDED = 'GET_FEELINGS_SUCCEEDED',
  GET_FEELINGS_FAILED = 'GET_FEELINGS_FAILED',
}

export default FeelingsActionType;
