enum ListMoodOfDepartmentActionType {
  GET_LIST_MOOD_OF_DEPARTMENT_REQUEST = 'GET_LIST_MOOD_OF_DEPARTMENT_REQUEST',
  GET_LIST_MOOD_OF_DEPARTMENT_SUCCEEDED = 'GET_LIST_MOOD_OF_DEPARTMENT_SUCCEEDED',
  GET_LIST_MOOD_OF_DEPARTMENT_FAILED = 'GET_LIST_MOOD_OF_DEPARTMENT_FAILED',
}

export default ListMoodOfDepartmentActionType;
