enum EmployeeMoodsActionType {
  GET_EMPLOYEE_MOODS_REQUEST = 'GET_EMPLOYEE_MOODS_REQUEST',
  GET_EMPLOYEE_MOODS_SUCCEEDED = 'GET_EMPLOYEE_MOODS_SUCCEEDED',
  GET_EMPLOYEE_MOODS_FAILED = 'GET_EMPLOYEE_MOODS_FAILED',
  SELECT_EMPLOYEE = 'SELECT_EMPLOYEE',
}

export default EmployeeMoodsActionType;
