enum UserActionType {
  POST_SIGNUP_REQUEST = 'POST_SIGNUP_REQUEST',
  POST_SIGNUP_SUCCEEDED = 'POST_SIGNUP_SUCCEEDED',
  POST_SIGNUP_FAILED = 'POST_SIGNUP_FAILED',

  POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST',
  POST_LOGIN_SUCCEEDED = 'POST_LOGIN_SUCCEEDED',
  POST_LOGIN_FAILED = 'POST_LOGIN_FAILED',
}

export default UserActionType;
