enum ListMoodOfEmployeeActionType {
  GET_LIST_MOOD_OF_EMPLOYEE_REQUEST = 'GET_LIST_MOOD_OF_EMPLOYEE_REQUEST',
  GET_LIST_MOOD_OF_EMPLOYEE_SUCCEEDED = 'GET_LIST_MOOD_OF_EMPLOYEE_SUCCEEDED',
  GET_LIST_MOOD_OF_EMPLOYEE_FAILED = 'GET_LIST_MOOD_OF_EMPLOYEE_FAILED',
  RESET_MOOD_OF_EMPLOYEE = 'RESET_MOOD_OF_EMPLOYEE',
}

export default ListMoodOfEmployeeActionType;
