enum EmployeeMoodsDetailsActionType {
  GET_EMPLOYEE_MONTH_MOODS_REQUEST = 'GET_EMPLOYEE_MONTH_MOODS_REQUEST',
  GET_EMPLOYEE_MONTH_MOODS_SUCCESSED = 'GET_EMPLOYEE_MONTH_MOODS_SUCCESSED',
  GET_EMPLOYEE_MONTH_MOODS_FAILED = 'GET_EMPLOYEE_MONTH_MOODS_FAILED',
}

export default EmployeeMoodsDetailsActionType;
