enum EmployeesActionType {
  GET_EMPLOYEES_REQUEST = 'GET_EMPLOYEES_REQUEST',
  GET_EMPLOYEES_SUCCEEDED = 'GET_EMPLOYEES_SYCCEEDED',
  GET_EMPLOYEES_FAILED = 'GET_EMPLOYEES_FAILED',
}

export default EmployeesActionType;
