enum JuniorFeelingsDetailsActionType {
  GET_JUNIOR_MONTH_FEELINGS_REQUEST = 'GET_JUNIOR_MONTH_FEELINGS_REQUEST',
  GET_JUNIOR_MONTH_FEELINGS_SUCCESSED = 'GET_JUNIOR_MONTH_FEELINGS_SUCCESSED',
  GET_JUNIOR_MONTH_FEELINGS_FAILED = 'GET_JUNIOR_MONTH_FEELINGS_FAILED',
}

export default JuniorFeelingsDetailsActionType;
